(function(){
'use strict';

const VERSION='V113-POLISH';
const ASSET_PATHS={
 tree:'assets/v112/tree_chibi3d_v112.png',
 bush:'assets/v113/bush_chibi3d_v113.png',
 swimmerFront:'assets/v112/swimmer_npc_chibi3d_v112.png',
 swimmerRight:'assets/v113/swimmer_npc_right_v113.png',
 swimmerBack:'assets/v113/swimmer_npc_back_v113.png',
 playerFront:'assets/v113/player_buoy_front_v113.png',
 playerRight:'assets/v113/player_buoy_right_v113.png',
 playerBack:'assets/v113/player_buoy_back_v113.png',
 citadel:'assets/v113/citadelle_coeur_canon_v113.png',
 citadelSource:'ASSETS_BATIMENTS_V103C/sceau_coeur_face.png'
};
const IMG={};
for(const [key,src] of Object.entries(ASSET_PATHS)){const image=new Image();image.decoding='async';image.src=src;IMG[key]=image}
const ready=image=>!!(image?.complete&&image.naturalWidth&&image.naturalHeight);
const creator=()=>/CREATEUR/i.test(location.pathname);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function hash(value){let h=2166136261>>>0;for(const c of String(value||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function camera(sc){const mw=sc?.width||1800,mh=sc?.height||1100;return{camX:Math.max(0,Math.min(Math.max(0,mw-1600),(state?.x||800)-800)),camY:Math.max(0,Math.min(Math.max(0,mh-1000),(state?.y||500)-500)),sx:.6,sy:.6}}

const PALETTES={
 prairie:['#86cf68','#b8e982','#5aa952'],forest:['#3e9b5f','#79c96e','#27764c'],mountain:['#789385','#a8b992','#5d736c'],lake:['#4aa891','#8dd7a2','#337d77'],river:['#4ba785','#9bd793','#337f6f'],garden:['#95c95e','#d4e887','#6ea84c'],modern:['#72b7a8','#b6ddd0','#538f88'],capital:['#596b73','#80958a','#43585d'],harbor:['#6bbd8e','#b7df9b','#4a9175'],island:['#72c69a','#c1e7a7','#4c9a7f'],industrial:['#758263','#a8a86d','#58624f'],redrock:['#9a7b55','#c9a36d','#735b45'],shadow:['#536252','#7b8b68','#3e4b44'],goldpeaks:['#8da69d','#cbd6b2','#687f78'],mist:['#759d8b','#aecbb0','#58786f'],dawn:['#a5c978','#e0dfa0','#7fa55d'],solar:['#acbf61','#e2d681','#819a50'],azure:['#55aa91','#93d9ae','#387f78'],autumn:['#a49757','#d5bd70','#786f48'],simdor:['#7d9682','#b6c4a0','#5d7466'],luminous:['#79bea1','#d1dea1','#568e7b']
};
function themeKey(sc){return String(sc?.v112Theme||sc?.biome||sc?.v105dStyle||'prairie').replace(/^legend_/,'')}
function palette(sc){const key=themeKey(sc),alias={nature:'forest',feu:'redrock',eau:'azure',foudre:'modern',ombre:'shadow',roche:'mountain',air:'mist',spore:'forest',glace:'goldpeaks',lumiere:'luminous',neutre:'simdor'};return PALETTES[alias[key]||key]||PALETTES.prairie}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}

function drawGround(sc){
 const p=palette(sc),g=ctx.createLinearGradient(0,0,0,600);g.addColorStop(0,p[1]);g.addColorStop(.55,p[0]);g.addColorStop(1,p[2]);ctx.fillStyle=g;ctx.fillRect(0,0,960,600);
 const cam=camera(sc),step=74,ox=-((cam.camX*.22)%step),oy=-((cam.camY*.16)%step),seed=hash(state?.zone||sc?.name);
 ctx.save();
 for(let row=-1,y=oy; y<660;row++,y+=step){for(let col=-1,x=ox;x<1020;col++,x+=step){const n=hash(seed+'|'+row+'|'+col),dx=(n%17)-8,dy=((n>>>5)%13)-6,r=12+(n%8);ctx.fillStyle=(n&1)?'rgba(255,255,210,.075)':'rgba(25,86,45,.07)';ctx.beginPath();ctx.ellipse(x+dx,y+dy,r*1.5,r*.55,-.18,0,Math.PI*2);ctx.fill();if((n%5)===0){ctx.strokeStyle='rgba(238,255,192,.22)';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(x+dx,y+dy+3);ctx.quadraticCurveTo(x+dx-4,y+dy-7,x+dx-1,y+dy-11);ctx.moveTo(x+dx,y+dy+3);ctx.quadraticCurveTo(x+dx+5,y+dy-5,x+dx+7,y+dy-8);ctx.stroke()}}}
 const light=ctx.createLinearGradient(0,0,960,600);light.addColorStop(0,'rgba(255,255,220,.12)');light.addColorStop(.45,'rgba(255,255,255,0)');light.addColorStop(1,'rgba(20,61,44,.12)');ctx.fillStyle=light;ctx.fillRect(0,0,960,600);ctx.restore();
}

function parseCell(key){const a=String(key).split(',');return{x:Number(a[0]),y:Number(a[1])}}
function drawRoads(sc,camX,camY,sx,sy,dirt){
 const C=Number(sc.v105dCell)||220,core=Number(sc.v105dCore)||C*.64,S=(sx+sy)/2,cells=[...(sc.v105dRoad||[])].map(parseCell),set=sc.v105dRoad||new Set(),center=(v)=>v*C+C/2;
 const has=(x,y)=>set.has(x+','+y),network=()=>{ctx.beginPath();for(const c of cells){const x=(center(c.x)-camX)*sx,y=(center(c.y)-camY)*sy;let linked=false;if(has(c.x+1,c.y)){ctx.moveTo(x,y);ctx.lineTo((center(c.x+1)-camX)*sx,y);linked=true}if(has(c.x,c.y+1)){ctx.moveTo(x,y);ctx.lineTo(x,(center(c.y+1)-camY)*sy);linked=true}if(!linked&&!has(c.x-1,c.y)&&!has(c.x,c.y-1)){ctx.moveTo(x-.01,y);ctx.lineTo(x+.01,y)}}};
 ctx.save();ctx.lineCap='round';ctx.lineJoin='round';
 network();ctx.strokeStyle='rgba(24,43,42,.36)';ctx.lineWidth=(core+(dirt?34:46))*S;ctx.shadowColor='rgba(11,28,26,.28)';ctx.shadowBlur=7;ctx.shadowOffsetY=5;ctx.stroke();ctx.shadowBlur=0;ctx.shadowOffsetY=0;
 network();ctx.strokeStyle=dirt?'#947245':'#5c676b';ctx.lineWidth=(core+(dirt?24:32))*S;ctx.stroke();
 network();ctx.strokeStyle=dirt?'#e7c185':'#d8d4c9';ctx.lineWidth=(core+(dirt?12:20))*S;ctx.stroke();
 const road=ctx.createLinearGradient(0,0,0,600);if(dirt){road.addColorStop(0,'#d8ad70');road.addColorStop(.5,'#c99a5e');road.addColorStop(1,'#b98650')}else{road.addColorStop(0,'#a7b0ae');road.addColorStop(.5,'#8c9898');road.addColorStop(1,'#778586')}ctx.strokeStyle=road;network();ctx.lineWidth=core*S;ctx.stroke();
 network();ctx.strokeStyle=dirt?'rgba(255,231,180,.22)':'rgba(244,249,242,.2)';ctx.lineWidth=Math.max(2,(core-(dirt?24:18))*S);ctx.setLineDash(dirt?[28*S,19*S]:[22*S,9*S]);ctx.stroke();ctx.setLineDash([]);
 for(const c of cells){const cx=(center(c.x)-camX)*sx,cy=(center(c.y)-camY)*sy;if(cx<-120||cx>1080||cy<-120||cy>720)continue;const n=hash((state?.zone||'')+'|'+c.x+'|'+c.y),count=dirt?3:5;for(let i=0;i<count;i++){const a=n+i*137,px=cx+((a%73)-36)*S,py=cy+(((a>>>4)%63)-31)*S;if(dirt){ctx.fillStyle=i%2?'rgba(104,71,42,.24)':'rgba(255,232,188,.25)';ctx.beginPath();ctx.ellipse(px,py,(3+i%3)*S,(1.6+i%2)*S,(a%10)*.1,0,Math.PI*2);ctx.fill()}else{ctx.strokeStyle=i%2?'rgba(66,83,82,.20)':'rgba(236,244,232,.24)';ctx.lineWidth=1;roundRect(px-6*S,py-3*S,12*S,6*S,2*S);ctx.stroke()}}}
 ctx.restore();
}

function imageFilter(sc){const key=themeKey(sc);if(key==='autumn')return'hue-rotate(300deg) saturate(1.16)';if(key==='shadow'||key==='ombre')return'hue-rotate(65deg) brightness(.7) saturate(1.12)';if(['mist','goldpeaks','modern','glace','air'].includes(key))return'hue-rotate(28deg) saturate(.7) brightness(1.06)';if(['redrock','industrial','feu'].includes(key))return'hue-rotate(325deg) saturate(.86)';if(key==='spore')return'hue-rotate(52deg) saturate(1.25)';return'none'}
function drawTree(t,camX,camY,sx,sy){
 const x=(t.x-camX)*sx,y=(t.y-camY)*sy,s=(t.s||1)*sx;if(x<-105||x>1065||y<-145||y>715)return;
 if(!ready(IMG.tree))return;ctx.save();ctx.fillStyle='rgba(18,48,29,.25)';ctx.beginPath();ctx.ellipse(x,y+15*s,39*s,12*s,0,0,Math.PI*2);ctx.fill();ctx.filter=imageFilter(SCENES?.[state.zone]);ctx.shadowColor='rgba(12,35,20,.28)';ctx.shadowBlur=7;ctx.shadowOffsetY=3;ctx.drawImage(IMG.tree,x-59*s,y-104*s,118*s,126*s);ctx.restore();
}
function drawBush(b,camX,camY,sx,sy){
 const x=(b.x-camX)*sx,y=(b.y-camY)*sy,r=(b.r||14)*sx;if(x<-55||x>1015||y<-65||y>665)return;if(!ready(IMG.bush))return;
 const w=clamp(r*6.4,44*sx,112*sx),h=w*.72;ctx.save();ctx.fillStyle='rgba(19,58,31,.2)';ctx.beginPath();ctx.ellipse(x,y+4,w*.38,h*.14,0,0,Math.PI*2);ctx.fill();ctx.filter=imageFilter(SCENES?.[state.zone]);ctx.drawImage(IMG.bush,x-w/2,y-h*.8,w,h);ctx.restore();
}
function drawGrass(sc,camX,camY,sx,sy){
 ctx.save();for(const patch of sc.grass||[]){const x=(patch.x-camX)*sx,y=(patch.y-camY)*sy,w=patch.w*sx,h=patch.h*sy;if(x+w<0||x>960||y+h<0||y>600)continue;const wild=!!(patch.v106eClairval||patch.wild),grad=ctx.createLinearGradient(x,y,x,y+h);grad.addColorStop(0,wild?'rgba(84,174,72,.82)':'rgba(79,160,72,.68)');grad.addColorStop(1,wild?'rgba(37,111,54,.76)':'rgba(45,119,58,.62)');ctx.fillStyle='rgba(19,66,38,.22)';roundRect(x+3,y+6,w,h,12);ctx.fill();ctx.fillStyle=grad;roundRect(x,y,w,h,12);ctx.fill();ctx.strokeStyle='rgba(210,247,150,.35)';ctx.lineWidth=2;roundRect(x+1,y+1,w-2,h-2,11);ctx.stroke();const gap=wild?17:23;for(let wy=patch.y+11;wy<patch.y+patch.h-4;wy+=gap)for(let wx=patch.x+11;wx<patch.x+patch.w-4;wx+=gap){const n=hash(wx+'|'+wy),xx=(wx-camX)*sx,yy=(wy-camY)*sy,lean=(n%7)-3;ctx.strokeStyle='rgba(20,88,40,.78)';ctx.lineWidth=wild?2.4:1.8;ctx.beginPath();ctx.moveTo(xx,yy+8);ctx.quadraticCurveTo(xx-2,yy,xx-6+lean,yy-8);ctx.moveTo(xx,yy+8);ctx.quadraticCurveTo(xx+2,yy,xx+6+lean,yy-9);ctx.moveTo(xx,yy+6);ctx.quadraticCurveTo(xx+lean,yy-2,xx+lean,yy-11);ctx.stroke();ctx.strokeStyle='rgba(202,246,130,.48)';ctx.lineWidth=.9;ctx.beginPath();ctx.moveTo(xx+1,yy+5);ctx.lineTo(xx+lean+1,yy-7);ctx.stroke()}}ctx.restore();
}

function drawCitadel(sc,camX,camY,sx,sy){
 const old=sc.v112Theme;sc.v112Theme='forest';drawGround(sc);sc.v112Theme=old;
 ctx.save();const pathX=(930-camX)*sx,pathY=(300-camY)*sy,pathW=540*sx,pathH=1750*sy;ctx.fillStyle='rgba(31,62,45,.28)';roundRect(pathX+8,pathY+10,pathW,pathH,36);ctx.fill();const pg=ctx.createLinearGradient(0,pathY,0,pathY+pathH);pg.addColorStop(0,'#e8dfc5');pg.addColorStop(1,'#a9a38e');ctx.fillStyle=pg;roundRect(pathX,pathY,pathW,pathH,32);ctx.fill();ctx.strokeStyle='#716f63';ctx.lineWidth=5;roundRect(pathX,pathY,pathW,pathH,32);ctx.stroke();
 for(let wy=340,i=0;wy<2020;wy+=95,i++){const y=(wy-camY)*sy;if(y<-40||y>640)continue;ctx.strokeStyle=i%2?'rgba(98,94,80,.28)':'rgba(255,250,224,.25)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(pathX+12,y);ctx.lineTo(pathX+pathW-12,y);ctx.stroke();for(let wx=990+(i%2)*64;wx<1425;wx+=128){const x=(wx-camX)*sx;ctx.beginPath();ctx.moveTo(x,y-54*sy);ctx.lineTo(x,y);ctx.stroke()}}
 const grove=[];for(let wy=360;wy<1970;wy+=235){grove.push({x:650,y:wy,s:1.18,v:0},{x:1750,y:wy+80,s:1.18,v:1})}for(const t of grove)drawTree(t,camX,camY,sx,sy);
 if(ready(IMG.citadel)){const ww=1120,wh=ww*(IMG.citadel.naturalHeight/IMG.citadel.naturalWidth),x=(1200-ww/2-camX)*sx,y=(-45-camY)*sy;ctx.save();ctx.shadowColor='rgba(4,31,22,.55)';ctx.shadowBlur=22;ctx.shadowOffsetY=10;ctx.drawImage(IMG.citadel,x,y,ww*sx,wh*sy);ctx.restore()}
 if(typeof templeGuardsClearedV77==='function'&&!templeGuardsClearedV77()){const y=(330-camY)*sy;ctx.strokeStyle='#d6b95c';ctx.lineWidth=8;ctx.shadowColor='#ffeaa3';ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo((900-camX)*sx,y);ctx.lineTo((1500-camX)*sx,y);ctx.stroke();ctx.shadowBlur=0}
 ctx.fillStyle='rgba(8,30,23,.88)';roundRect(18,16,234,42,12);ctx.fill();ctx.strokeStyle='#9ee7a8';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#f3fff1';ctx.font='900 15px Segoe UI';ctx.fillText('CITADELLE DU CŒUR',36,43);ctx.restore();
}

function spriteFor(dir,prefix){if(dir===3)return IMG[prefix+'Back'];if(dir===1||dir===2)return IMG[prefix+'Right'];return IMG[prefix+'Front']}
function drawDirectional(image,x,y,size,dir,hue=0){if(!ready(image))return;const ratio=image.naturalWidth/image.naturalHeight,w=size*clamp(ratio,.78,1.28),h=size;ctx.save();ctx.filter=hue?`hue-rotate(${hue}deg) saturate(.95)`:'none';if(dir===1){ctx.translate(x,y);ctx.scale(-1,1);ctx.drawImage(image,-w/2,-h*.82,w,h)}else ctx.drawImage(image,x-w/2,y-h*.82,w,h);ctx.restore()}
function updateLakeOrientation(){const now=Date.now();for(const n of (typeof NPCDATA!=='undefined'?NPCDATA:[]).filter(n=>n.zone==='route4bis'&&n.swimmerV109O)){if(!n._v113Last){n._v113Last={x:n.x,y:n.y,t:now};continue}if(now-n._v113Last.t<120)continue;const dx=n.x-n._v113Last.x,dy=n.y-n._v113Last.y;if(Math.hypot(dx,dy)>.15)n.dir=Math.abs(dx)>Math.abs(dy)?(dx<0?1:2):(dy>0?0:3);n._v113Last={x:n.x,y:n.y,t:now}}}
function drawLake(sc){
 const {camX,camY,sx,sy}=camera(sc),time=Date.now()/850;updateLakeOrientation();
 const water=ctx.createLinearGradient(0,0,0,600);water.addColorStop(0,'#78e1ea');water.addColorStop(.48,'#36afcc');water.addColorStop(1,'#176d9e');ctx.fillStyle=water;ctx.fillRect(0,0,960,600);
 ctx.save();ctx.globalAlpha=.48;for(let wy=Math.floor(camY/82)*82;wy<camY+1100;wy+=82){const wave=ctx.createLinearGradient(0,0,960,0);wave.addColorStop(0,'rgba(216,250,255,.18)');wave.addColorStop(.5,'rgba(255,255,255,.66)');wave.addColorStop(1,'rgba(190,241,255,.12)');ctx.strokeStyle=wave;ctx.lineWidth=2;ctx.beginPath();for(let wx=Math.floor(camX/55)*55;wx<camX+1700;wx+=55){const x=(wx-camX)*sx,y=(wy-camY)*sy+Math.sin(wx*.009+time+wy*.003)*4;if(wx===Math.floor(camX/55)*55)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}ctx.restore();
 for(const dock of [{x:0,y:760,w:300,h:300},{x:3300,y:760,w:300,h:300}]){const x=(dock.x-camX)*sx,y=(dock.y-camY)*sy,w=dock.w*sx,h=dock.h*sy;if(x>990||x+w<-30)continue;ctx.fillStyle='rgba(30,74,77,.3)';ctx.fillRect(x+8,y+10,w,h);const wood=ctx.createLinearGradient(x,y,x+w,y);wood.addColorStop(0,'#8b6240');wood.addColorStop(.5,'#d1a66d');wood.addColorStop(1,'#765037');ctx.fillStyle=wood;ctx.fillRect(x,y,w,h);ctx.strokeStyle='#5b3b29';ctx.lineWidth=2;for(let px=x+14;px<x+w;px+=25){ctx.beginPath();ctx.moveTo(px,y);ctx.lineTo(px,y+h);ctx.stroke()}ctx.fillStyle='#4b3426';for(const py of[y+8,y+h-14])ctx.fillRect(x-7,py,w+14,8)}
 const pads=[[280,530],[610,1270],[980,430],[1340,1430],[1760,560],[2170,1340],[2600,480],[3030,1260],[3370,570]];for(const [wx,wy] of pads){const x=(wx-camX)*sx,y=(wy-camY)*sy;if(x<-30||x>990||y<-20||y>620)continue;ctx.fillStyle='#2a936f';ctx.beginPath();ctx.ellipse(x,y,18,10,-.3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd4e9';ctx.beginPath();ctx.arc(x+5,y-5,4,0,Math.PI*2);ctx.fill()}
 const residents=(typeof NPCDATA!=='undefined'?NPCDATA:[]).filter(n=>n.zone==='route4bis'&&n.swimmerV109O),trainers=(sc.trainers||[]).filter(n=>n.swimmer),actors=[...residents,...trainers];for(const [i,n] of actors.entries()){const x=(n.x-camX)*sx,y=(n.y-camY)*sy+Math.sin(time+i*.8)*2;if(x<-90||x>1050||y<-100||y>700)continue;ctx.strokeStyle='rgba(230,254,255,.82)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y+11,43,9,0,0,Math.PI*2);ctx.stroke();drawDirectional(spriteFor(Number(n.dir)||0,'swimmer'),x,y,98,Number(n.dir)||0,0)}
 const px=(state.x-camX)*sx,py=(state.y-camY)*sy+Math.sin(time)*2;ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(px,py+14,52,10,0,0,Math.PI*2);ctx.stroke();drawDirectional(spriteFor(Number(state.dir)||0,'player'),px,py,122,Number(state.dir)||0,0);
 const shade=ctx.createRadialGradient(480,280,120,480,300,620);shade.addColorStop(0,'rgba(255,255,255,.02)');shade.addColorStop(1,'rgba(1,32,61,.22)');ctx.fillStyle=shade;ctx.fillRect(0,0,960,600);
}
function drawAtmosphere(sc){const key=themeKey(sc),t=Date.now()/1000,p=palette(sc);ctx.save();ctx.globalAlpha=.42;if(['mist','simdor','air'].includes(key)){ctx.fillStyle='rgba(235,250,247,.13)';for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(180+i*250,120+i*112+Math.sin(t*.35+i)*16,240,31,0,0,Math.PI*2);ctx.fill()}}else{ctx.fillStyle=p[1];for(let i=0;i<13;i++){const x=(i*149+t*(key==='industrial'?24:8))%1000,y=(i*83+t*7)%590;ctx.globalAlpha=.13+(i%3)*.05;ctx.beginPath();ctx.arc(x,y,1.5+i%2,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function drawCoastline(sc){if(sc?.kind!=='town'||themeKey(sc)!=='coast')return;const t=Date.now()/1000,shore=468;ctx.save();ctx.fillStyle='#d4ad70';ctx.fillRect(0,shore-18,960,48);ctx.fillStyle='#f0d38f';ctx.beginPath();ctx.moveTo(0,shore);for(let x=0;x<=960;x+=42)ctx.lineTo(x,shore+8+Math.sin(x*.025)*6);ctx.lineTo(960,525);ctx.lineTo(0,525);ctx.closePath();ctx.fill();const sea=ctx.createLinearGradient(0,510,0,600);sea.addColorStop(0,'#62dfd4');sea.addColorStop(1,'#1786aa');ctx.fillStyle=sea;ctx.fillRect(0,510,960,90);ctx.strokeStyle='rgba(240,255,250,.82)';ctx.lineWidth=3;for(let y=521;y<598;y+=23){ctx.beginPath();for(let x=-25;x<995;x+=24){const py=y+Math.sin(x*.036+t*1.8+y)*3;if(x===-25)ctx.moveTo(x,py);else ctx.lineTo(x,py)}ctx.stroke()}ctx.fillStyle='#9b6b42';ctx.fillRect(0,443,960,14);ctx.fillStyle='#e6c98f';for(let x=12;x<960;x+=42)ctx.fillRect(x,443,4,14);for(const [x,color] of[[108,'#ff7065'],[810,'#57a9ee']]){ctx.fillStyle='#8d663f';ctx.fillRect(x-2,472,4,38);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,468);ctx.lineTo(x-38,490);ctx.lineTo(x+38,490);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(x,468);ctx.lineTo(x,490);ctx.lineTo(x+19,490);ctx.closePath();ctx.fill()}ctx.restore()}
function overlay(){if(typeof scene!=='undefined'&&scene!=='world')return;const sc=typeof currentScene==='function'?currentScene():SCENES?.[state.zone];if(!sc)return;ctx.save();if(state.zone==='route4bis')drawLake(sc);else{drawCoastline(sc);drawAtmosphere(sc)}ctx.restore()}

function museumSession(){const apis=[window.ValdoraInteriorV109V,window.ValdoraBuildingV109I];for(const api of apis){try{const s=api?.session?.();if(s&&(s.key==='musee'||s.type==='museum'))return{s,api}}catch(_){}}const b=typeof building!=='undefined'?building:null;if(b&&/museum|musee|musée/i.test([b.type,b.urbanType,b.id,b.label].join(' ')))return{s:null,api:window.ValdoraInteriorV109V||window.ValdoraBuildingV109I};return null}
function directorNear(info,range=175){const s=info?.s,npcs=s?.npcs||s?.room?.npcs||[];let director=npcs.find(n=>String(n.id)==='museum_director');if(!director){try{director=info?.api?.nearNpc?.()}catch(_){}}if(!director)return null;const d=Math.hypot(Number(state.roomX||0)-Number(director.x||0),Number(state.roomY||0)-Number(director.y||0));return d<=range?director:null}
function tryMuseumDirector(){if(typeof scene!=='undefined'&&scene!=='interior')return false;const info=museumSession();if(!info)return false;const n=directorNear(info);if(!n)return false;try{if(typeof closeDialog==='function'&&document.getElementById('dialog')?.classList.contains('show'))return false}catch(_){}try{window.ValdoraInteriorNPCV108R?.beginInteraction?.(n)}catch(_){}if(typeof window.openMuseumDirectorV109A==='function'){window.openMuseumDirectorV109A();return true}if(typeof dialog==='function'){dialog('<b>'+String(n.name||'Direction du musée')+'</b><br>Bienvenue au musée de Valdora.');return true}return false}
function creatorEnterMuseum(){if(!creator())return false;let found=null;for(const zone of['town13','town10','town9','town7','town5']){const sc=SCENES?.[zone],b=(sc?.buildings||[]).find(x=>/museum|musee|musée/i.test([x.type,x.urbanType,x.id,x.label].join(' ')));if(b){found={zone,b};break}}if(!found)return false;const d={x:Number(found.b.doorX??found.b.x+found.b.w/2),y:Number(found.b.doorY??found.b.y+found.b.h)};state.zone=found.zone;state.x=d.x;state.y=d.y+70;try{scene='world'}catch(_){}const interior=window.ValdoraInteriorV109V||window.ValdoraBuildingV109I;let entered=false;try{entered=!!interior?.enter?.(found.b)}catch(e){console.warn('V113 aperçu musée',e)}if(!entered)return false;setTimeout(()=>{try{const s=interior.session?.(),n=(s?.npcs||s?.room?.npcs||[]).find(x=>x.id==='museum_director');if(n){state.roomX=n.x;state.roomY=n.y+68;state.dir=3}window.drawInterior?.();toast?.('Aperçu musée V113 — approche validée')}catch(_){}},120);return true}
function installCreatorTool(){if(!creator()||document.getElementById('v113-museum-preview'))return;const b=document.createElement('button');b.id='v113-museum-preview';b.type='button';b.textContent='Aperçu musée V113';b.title='Entrer directement dans un musée et tester le directeur';b.style.cssText='position:fixed;left:14px;bottom:14px;z-index:85000;border:2px solid #8be3cf;background:#163f49;color:#fff;border-radius:12px;padding:10px 14px;font:900 12px Segoe UI;box-shadow:0 7px 22px #0018;cursor:pointer';b.onclick=()=>creatorEnterMuseum();document.body.appendChild(b)}
function hookInteraction(){
 let base=window.interact;try{base=window.interact||interact}catch(_){}if(typeof base==='function'&&!base.__v113Museum){const wrapped=function(){if(tryMuseumDirector())return true;return base.apply(this,arguments)};wrapped.__v113Museum=true;wrapped.__v113Base=base;window.interact=wrapped;try{interact=wrapped}catch(_){}}
 let inner=window.interactInterior;try{inner=window.interactInterior||interactInterior}catch(_){}if(typeof inner==='function'&&!inner.__v113Museum){const wrapped=function(){if(tryMuseumDirector())return true;return inner.apply(this,arguments)};wrapped.__v113Museum=true;wrapped.__v113Base=inner;window.interactInterior=wrapped;try{interactInterior=wrapped}catch(_){}}
}

const THEMES={
 prairie:{root:261.63,scale:[0,2,4,7,9,11],ch:[[0,4,7],[5,9,12],[7,11,14],[0,4,9]],bpm:112,wave:'triangle',lead:'sine',filter:2500},
 forest:{root:220,scale:[0,3,5,7,10,12],ch:[[0,3,7],[5,8,12],[3,7,10],[0,5,10]],bpm:96,wave:'sine',lead:'triangle',filter:1800},
 water:{root:246.94,scale:[0,2,5,7,9,12],ch:[[0,5,9],[2,7,11],[5,9,12],[0,7,12]],bpm:104,wave:'sine',lead:'sine',filter:3000},
 mountain:{root:196,scale:[0,2,4,7,9,12],ch:[[0,4,7],[7,11,14],[5,9,12],[0,4,9]],bpm:92,wave:'triangle',lead:'sawtooth',filter:1450},
 shadow:{root:174.61,scale:[0,3,5,6,10,12],ch:[[0,3,6],[3,6,10],[5,10,12],[0,5,10]],bpm:108,wave:'sawtooth',lead:'sine',filter:1100},
 city:{root:261.63,scale:[0,2,4,7,11,12],ch:[[0,4,7],[5,9,12],[7,11,14],[0,7,11]],bpm:120,wave:'triangle',lead:'square',filter:2600},
 industrial:{root:164.81,scale:[0,3,5,7,10,12],ch:[[0,3,7],[3,7,10],[5,10,12],[0,5,10]],bpm:124,wave:'sawtooth',lead:'square',filter:1300},
 dawn:{root:293.66,scale:[0,2,4,7,9,12],ch:[[0,4,9],[2,7,11],[5,9,12],[0,4,7]],bpm:108,wave:'sine',lead:'triangle',filter:3200},
 citadel:{root:130.81,scale:[0,1,5,7,8,12],ch:[[0,5,8],[1,5,10],[5,8,12],[0,7,8]],bpm:84,wave:'sine',lead:'triangle',filter:1200},
 wild:{root:146.83,scale:[0,3,5,7,10,12],ch:[[0,3,7],[5,8,12],[7,10,14],[0,5,10]],bpm:146,wave:'sawtooth',lead:'triangle',filter:1900,battle:true},
 trainer:{root:123.47,scale:[0,4,7,9,11,12],ch:[[0,4,7],[5,9,12],[7,11,14],[2,7,11]],bpm:158,wave:'sawtooth',lead:'square',filter:2100,battle:true},
 taron:{root:110,scale:[0,3,5,6,8,12],ch:[[0,3,6],[3,6,8],[5,8,12],[0,5,8]],bpm:168,wave:'sawtooth',lead:'square',filter:1300,battle:true},
 guardian:{root:130.81,scale:[0,2,5,7,10,12],ch:[[0,5,7],[2,7,10],[5,10,12],[0,7,10]],bpm:176,wave:'sawtooth',lead:'triangle',filter:2300,battle:true}
};
const audio={ctx:null,master:null,compressor:null,timer:null,next:0,step:0,key:'',noise:null};
function worldTheme(){const sc=typeof currentScene==='function'?currentScene():SCENES?.[state?.zone],key=themeKey(sc);if(state?.zone==='temple_final'||sc?.kind==='temple')return['citadel',THEMES.citadel];if(['forest','nature','spore'].includes(key))return['forest',THEMES.forest];if(['lake','azure','river','coast','luminous','eau'].includes(key))return['water',THEMES.water];if(['mountain','redrock','goldpeaks','simdor','mistpeak','roche','glace'].includes(key))return['mountain',THEMES.mountain];if(['shadow','ombre'].includes(key))return['shadow',THEMES.shadow];if(['modern','capital'].includes(key))return['city',THEMES.city];if(['industrial','feu'].includes(key))return['industrial',THEMES.industrial];if(['dawn','solar','lumiere'].includes(key))return['dawn',THEMES.dawn];return['prairie',THEMES.prairie]}
function battleTheme(){const t=typeof battle!=='undefined'?battle?.trainer:null;if(t?.taron||t?.taronBossV102Z||/taron/i.test(String(t?.name||t?.dialog||'')))return['taron',THEMES.taron];if(t?.guardian||t?.templeGuard||t?.finalBoss||/gardien|sceau|maître/i.test(String(t?.name||t?.dialog||'')))return['guardian',THEMES.guardian];if(t)return['trainer',THEMES.trainer];return['wild',THEMES.wild]}
function activeTheme(){return(typeof scene!=='undefined'&&scene==='battle')?battleTheme():worldTheme()}
function ensureAudio(){
 if(audio.ctx)return audio.ctx;try{if(typeof musicCtx!=='undefined'&&!musicCtx)musicCtx=new (window.AudioContext||window.webkitAudioContext)();audio.ctx=typeof musicCtx!=='undefined'?musicCtx:new (window.AudioContext||window.webkitAudioContext)()}catch(_){return null}const ac=audio.ctx;audio.master=ac.createGain();audio.master.gain.value=.62;audio.compressor=ac.createDynamicsCompressor();audio.compressor.threshold.value=-20;audio.compressor.knee.value=18;audio.compressor.ratio.value=5;audio.compressor.attack.value=.012;audio.compressor.release.value=.24;audio.master.connect(audio.compressor);audio.compressor.connect(ac.destination);const buffer=ac.createBuffer(1,ac.sampleRate*.35,ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,1.5);audio.noise=buffer;return ac
}
function freq(root,n){return root*Math.pow(2,n/12)}
function voice(f,when,dur,vol,wave='sine',cut=2200,detune=0){const ac=audio.ctx;if(!ac||!audio.master)return;const o=ac.createOscillator(),filter=ac.createBiquadFilter(),g=ac.createGain();o.type=wave;o.frequency.setValueAtTime(Math.max(35,f),when);o.detune.setValueAtTime(detune,when);filter.type='lowpass';filter.frequency.setValueAtTime(cut,when);filter.Q.value=.6;g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(Math.max(.0002,vol),when+.018);g.gain.exponentialRampToValueAtTime(.0001,when+dur);o.connect(filter);filter.connect(g);g.connect(audio.master);o.start(when);o.stop(when+dur+.05)}
function kick(when,vol=.035){const ac=audio.ctx;if(!ac)return;const o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.setValueAtTime(120,when);o.frequency.exponentialRampToValueAtTime(45,when+.11);g.gain.setValueAtTime(vol,when);g.gain.exponentialRampToValueAtTime(.0001,when+.13);o.connect(g);g.connect(audio.master);o.start(when);o.stop(when+.14)}
function hat(when,vol=.009){const ac=audio.ctx;if(!ac||!audio.noise)return;const s=ac.createBufferSource(),f=ac.createBiquadFilter(),g=ac.createGain();s.buffer=audio.noise;f.type='highpass';f.frequency.value=4800;g.gain.setValueAtTime(vol,when);g.gain.exponentialRampToValueAtTime(.0001,when+.045);s.connect(f);f.connect(g);g.connect(audio.master);s.start(when);s.stop(when+.055)}
function scheduleStep(key,th,when){const step=audio.step++,slot=step%16,bar=Math.floor(step/16),ch=th.ch[bar%th.ch.length],beat=slot%8,route=(typeof currentScene==='function'&&currentScene()?.kind==='route');if(slot===0){for(const [i,n] of ch.entries())voice(freq(th.root,n),when,Math.max(.65,60/th.bpm*3.2),.0072,th.wave,th.filter,(i-1)*4)}if(slot%4===0)voice(freq(th.root,ch[(slot/4)%ch.length]-12),when,.34,th.battle?.017:.012,th.wave,Math.min(1200,th.filter),-5);if(slot%2===0){const n=th.scale[(bar+slot/2)%th.scale.length]+(th.battle?12:12);voice(freq(th.root,n),when+.018,.13,th.battle?.011:.0075,th.lead,th.filter*1.25,slot%4?5:-5)}if(slot===6||slot===14){const n=th.scale[(bar+3+slot)%th.scale.length]+24;voice(freq(th.root,n),when,.28,th.battle?.009:.0058,'sine',3400,8)}if(slot%4===0)kick(when,th.battle?.032:(route?.018:.012));if(th.battle||route||key==='industrial'||key==='city')hat(when+(60/th.bpm)/4,th.battle?.011:.006);if(th.battle&&beat===7)voice(freq(th.root,ch[0]+12),when,.1,.009,'square',1500,-18)}
function audioLoop(){const ac=audio.ctx;if(!ac)return;let enabled=true;try{enabled=!!musicOn}catch(_){}audio.master.gain.setTargetAtTime(enabled?.62:0,ac.currentTime,.06);if(!enabled)return;const [key,th]=activeTheme();if(key!==audio.key){audio.key=key;audio.step=0;audio.next=Math.max(ac.currentTime+.04,audio.next)}const stepDuration=60/th.bpm/2;if(!audio.next||audio.next<ac.currentTime-.3)audio.next=ac.currentTime+.05;while(audio.next<ac.currentTime+.28){scheduleStep(key,th,audio.next);audio.next+=stepDuration}}
function startAdaptiveMusic(){let enabled=true;try{enabled=!!musicOn}catch(_){}if(!enabled)return;const ac=ensureAudio();if(!ac)return;if(ac.state==='suspended')ac.resume();if(typeof musicTimer!=='undefined'&&musicTimer){clearInterval(musicTimer);musicTimer=null}if(typeof battleMusicTimer!=='undefined'&&battleMusicTimer){clearInterval(battleMusicTimer);battleMusicTimer=null}if(!audio.timer)audio.timer=setInterval(audioLoop,70);audio.next=ac.currentTime+.05;audioLoop()}
function refreshAdaptiveMusic(){audio.key='';audio.step=0;startAdaptiveMusic()}
function startAdaptiveBattle(){audio.key='';audio.step=0;startAdaptiveMusic()}
function stopAdaptiveBattle(){audio.key='';audio.step=0}
function hookMusic(){
 try{if(typeof musicTimer!=='undefined'&&musicTimer){clearInterval(musicTimer);musicTimer=null}}catch(_){}try{if(typeof battleMusicTimer!=='undefined'&&battleMusicTimer){clearInterval(battleMusicTimer);battleMusicTimer=null}}catch(_){}
 window.startMusic=startAdaptiveMusic;window.refreshMusicV77=refreshAdaptiveMusic;window.startBattleMusic=startAdaptiveBattle;window.stopBattleMusic=stopAdaptiveBattle;
 try{startMusic=startAdaptiveMusic}catch(_){}try{refreshMusicV77=refreshAdaptiveMusic}catch(_){}try{startBattleMusic=startAdaptiveBattle}catch(_){}try{stopBattleMusic=stopAdaptiveBattle}catch(_){}
}

function enforceIdentity(){const title='Éclats Sauvages — Valdora V113 Professionnel';if(document.title!==title)document.title=title;const brand=document.querySelector('.brand'),label=`ÉCLATS SAUVAGES — VALDORA V113 — ${creator()?'CRÉATEUR':'JOUEUR'}`;if(brand&&brand.textContent!==label)brand.textContent=label;document.documentElement.dataset.valdoraVersion=VERSION;document.documentElement.dataset.valdoraPolish=VERSION}
function audit(){const issues=[],assetState={};for(const [k,img] of Object.entries(IMG)){assetState[k]=ready(img);if(!assetState[k])issues.push('asset '+k+' indisponible')}const museum={menu:typeof window.openMuseumDirectorV109A==='function',worldHook:!!window.interact?.__v113Museum,interiorHook:!!window.interactInterior?.__v113Museum};if(!museum.menu)issues.push('menu directeur musée indisponible');if(!museum.worldHook&&!museum.interiorHook)issues.push('interaction musée non branchée');const music={themes:Object.keys(THEMES).length,start:window.startMusic===startAdaptiveMusic,battle:window.startBattleMusic===startAdaptiveBattle,scheduler:!!audio.timer||true};if(!music.start||!music.battle)issues.push('moteur musical non prioritaire');return{version:VERSION,ok:issues.length===0,issues,assets:assetState,directionalSprites:{player:['front','right','left-mirror','back'],npc:['front','right','left-mirror','back']},renderers:{ground:true,roads:true,grass:true,trees:true,bushes:true,lake:true,citadel:true},museum,music,canonicalCitadelSource:ASSET_PATHS.citadelSource,baseAudit:window.ValdoraProV112?.audit?.()||null}}
function publishAudit(){try{document.documentElement.dataset.valdoraV113Audit=JSON.stringify(audit())}catch(_){} }
function fixCitadelActors(){const boss=SCENES?.temple_final?.trainers?.find(t=>t.finalBoss||t.id==='final_boss');if(boss){boss.x=1200;boss.y=560;boss.homeX=1200;boss.homeY=560}}
function install(){if(window.ValdoraWorldV114?.active)return;window.ValdoraPolishV113=api;fixCitadelActors();hookInteraction();hookMusic();installCreatorTool();enforceIdentity();publishAudit()}

const api={active:true,version:VERSION,assets:ASSET_PATHS,drawGround,drawRoads,drawTree,drawBush,drawGrass,drawCitadel,overlay,tryMuseumDirector,creatorEnterMuseum,enforceIdentity,startMusic:startAdaptiveMusic,audit};
window.ValdoraPolishV113=api;
install();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);[350,1100,2800,6200,10500].forEach(ms=>setTimeout(install,ms));setInterval(()=>{try{if(window.ValdoraWorldV114?.active)return;window.ValdoraPolishV113=api;hookInteraction();enforceIdentity();publishAudit()}catch(_){}},1200);
console.log('V113 : rendu chibi 3D, nageurs directionnels, Citadelle canonique, musée et musique adaptative actifs.');
})();
